ACME_HOST = "localhost"
ACME_PORT = "8080"
ACME_URL = f"http://{ACME_HOST}:{ACME_PORT}"

MAIN_SERVER_HOST = "localhost"  
MAIN_SERVER_PORT = "5000"
MAIN_SERVER_URL = f"http://{MAIN_SERVER_HOST}:{MAIN_SERVER_PORT}"